### ISSUE TITLE
It's possible to kick self out of a room

### ISSUE THREAD

**Issue by lvictorino** [Elao/curvytron#133]
I don't know if it's related to [#127](https://github.com/Elao/curvytron/issues/127) but if one creates a room, he can click on the small cross near his name to kick himself and the room ends up as being empty but player is "still in lobby".

**Comment by Tom32i** [comment]
Yeah, because your player is just a default local player, named after you profile, that is automatically added to save you time.

But we can consider moving to a system where you always has at least one local player (so you can't remove it) that matches your profile. 

That new system would make even more sens with the account feature.
